/**
 * skill_generate - Self-generating skill (v5.1.0)
 *
 * Skill generator — ihtiyaca gore skill uretir
 *
 * Akis:
 * 1. Kullanici bir istek yapar (ornek: "tum pdf'leri birlestir")
 * 2. Mevcut tool/skill'ler yoksa bu tool cagirilir
 * 3. LLM'a skill taslagi uretmesi icin istek gonderilir
 * 4. SKILL.md dosyasi yazilir, kaydedilir, hemen kullanilir
 */

const fs = require("fs");
const { istemciSec } = require("../utils/http-secici");
const path = require("path");
const os = require("os");

const SKILLS_DIR = path.join(os.homedir(), ".natureco", "skills");

// Ortak ayar modülü üzerinden okunur; dosyayı doğrudan okumak çalışma
// anında doğan sağlayıcıları (ör. abonelik köprüsü) görmez.
function getConfig() { return require("../utils/config").getConfig(); }

function isMiniMax(url) {
  return url && (url.includes("minimax.io") || url.includes("minimaxi.com"));
}

function apiRequest(url, key, body) {
  return new Promise((resolve, reject) => {
    const isMM = isMiniMax(url);
    const endpoint = isMM
      ? url.replace(/\/$/, "") + "/v1/text/chatcompletion_v2"
      : url.replace(/\/$/, "") + "/chat/completions";
    const req = istemciSec(endpoint).request(endpoint, {
      method: "POST",
      headers: { "Authorization": "Bearer " + key, "Content-Type": "application/json" },
      timeout: 30000,
    }, res => {
      let data = "";
      res.on("data", c => data += c);
      res.on("end", () => {
        if (res.statusCode === 200) {
          try { resolve(JSON.parse(data)); } catch (e) { reject(new Error("Parse hatasi")); }
        } else reject(new Error("HTTP " + res.statusCode + ": " + data.slice(0, 200)));
      });
    });
    req.on("error", reject);
    req.on("timeout", () => req.destroy() && reject(new Error("Timeout")));
    req.write(JSON.stringify(body));
    req.end();
  });
}

function slugify(text) {
  return (text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "custom-skill";
}

async function generateSkillInstructions(taskDescription, skillName) {
  const cfg = getConfig();
  if (!cfg.providerUrl || !cfg.providerApiKey) {
    throw new Error("Provider ayarli degil. Once: natureco setup");
  }
  const promptText = "Sen NatureCo CLI icin SKILL talimatlari yazarsin. Asagidaki gorev icin System Prompt'a eklenecek Turkce talimat yaz:\n\nGOREV: " + taskDescription + "\n\nKURALLAR:\n- Turkce, kisa, oz, madde madde yaz\n- 5-10 satir, dogrudan uygulanabilir\n- Hangi araclarin kullanilacagi (dosya/shell/web) acikca belirt\n- Ornek bir kucuk kullanim ornegi ekle\n- Yanlis ciktilari nasil onlenmesi gerektigini yaz\n\nDirekt SKILL.md icerigini yaz, baska aciklama yapma.";

  const body = {
    model: cfg.providerModel || "MiniMax-M2.5",
    messages: [
      { role: "system", content: "Sen bir CLI skill talimat yazarsin. Kisa ve net Turkce yaz. Markdown kullanma, duz metin yaz." },
      { role: "user", content: promptText },
    ],
    temperature: 0.5,
    max_tokens: 1500,
  };
  const res = await apiRequest(cfg.providerUrl, cfg.providerApiKey, body);
  const content = res.choices && res.choices[0] && res.choices[0].message ? (res.choices[0].message.content || "") : "";
  return content.trim();
}

async function generateSkill(params) {
  const taskDescription = params.taskDescription;
  const requestedName = params.skillName;
  if (!taskDescription) return { success: false, error: "taskDescription gerekli" };

  const skillName = requestedName || slugify(taskDescription);
  const skillDir = path.join(SKILLS_DIR, skillName);

  if (fs.existsSync(skillDir)) {
    return { success: true, message: "Skill zaten mevcut", path: skillDir, skillName: skillName, alreadyExisted: true };
  }

  let skillContent;
  try {
    skillContent = await generateSkillInstructions(taskDescription, skillName);
  } catch (e) {
    return { success: false, error: "Skill talimati uretilemedi: " + e.message };
  }

  if (!skillContent || skillContent.length < 50) {
    return { success: false, error: "LLM bos icerik uretti" };
  }

  fs.mkdirSync(skillDir, { recursive: true });
  fs.writeFileSync(path.join(skillDir, "SKILL.md"), skillContent, "utf8");
  const meta = {
    name: skillName,
    description: "Otomatik uretildi: " + taskDescription.slice(0, 100),
    author: "skill_generate (auto)",
    version: "1.0.0",
    tags: ["auto-generated", "user-created"],
    autoGenerated: true,
    taskDescription: taskDescription,
    createdAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(skillDir, "metadata.json"), JSON.stringify(meta, null, 2), "utf8");

  return {
    success: true,
    message: "Yeni skill olusturuldu ve hemen kullanilabilir!",
    skillName: skillName,
    path: skillDir,
    content: skillContent.slice(0, 300),
    note: "REPL'i yeniden acarsaniz yeni skill yuklenecek. /skills list ile test edebilirsiniz.",
  };
}

module.exports = {
  name: "skill_generate",
  description: "Olmayan bir ozellik icin LLM ile yeni bir skill talimati uretir, kaydeder ve hemen kullanima sunar. 'PDF birlestir', 'JSON duzenle' gibi gorevler icin.",
  inputSchema: {
    type: "object",
    properties: {
      taskDescription: { type: "string", description: "Skill'in ne yapacagi (ornek: 'PDF dosyalarini tek dosyada birlestir')" },
      skillName: { type: "string", description: "Ozel skill adi (opsiyonel, otomatik uretilir)" },
    },
    required: ["taskDescription"],
  },
  async execute(params) {
    return await generateSkill(params);
  },
};
